"""
Django settings for PolygonMigration project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv


# ---------------------------------------------------------------------------
# Base configuration
# ---------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment variables from .env.
# Secrets and credentials must not be committed to Git.
load_dotenv(os.path.join(BASE_DIR, ".env"))


# ---------------------------------------------------------------------------
# Security / Django core
# ---------------------------------------------------------------------------

SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DEBUG", "False").strip().lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# ---------------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "problems",
    "users",
    "contents",
]


# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ---------------------------------------------------------------------------
# URL / application entry points
# ---------------------------------------------------------------------------

ROOT_URLCONF = "PolygonMigration.urls"

WSGI_APPLICATION = "PolygonMigration.wsgi.application"


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "OPTIONS": {
            "client_encoding": "UTF8",
        },
    }
}


# ---------------------------------------------------------------------------
# Authentication / password validation
# ---------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    "users.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# ---------------------------------------------------------------------------
# Internationalization
# ---------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------------

STATIC_URL = "static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# ---------------------------------------------------------------------------
# Django defaults
# ---------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Session lifetime: 1 day.
SESSION_COOKIE_AGE = 86400


# ---------------------------------------------------------------------------
# Polygon API
# ---------------------------------------------------------------------------

POLYGON_API_KEY = os.getenv("POLYGON_API_KEY")

POLYGON_API_SECRET = os.getenv("POLYGON_API_SECRET")

if not POLYGON_API_KEY or not POLYGON_API_SECRET:
    raise Exception(
        "POLYGON_API_KEY and POLYGON_API_SECRET must be set "
        "in the .env file"
    )


# ---------------------------------------------------------------------------
# Storage provider
# ---------------------------------------------------------------------------
#
# Polygon migration code uses the provider abstraction instead of depending
# directly on Azure-specific classes.
#
# Current supported provider:
#     azure
#
# Example:
#     STORAGE_PROVIDER=azure
#

STORAGE_PROVIDER = os.getenv("STORAGE_PROVIDER", "azure").strip().lower()


# ---------------------------------------------------------------------------
# Azure Blob Storage
# ---------------------------------------------------------------------------
#
# Credentials are loaded exclusively from environment variables.
# Do not hard-code any of these values.
#
# Authentication uses an Azure service principal:
#     tenant ID
#     client ID
#     client secret
#

AZURE_STORAGE_ACCOUNT_URL = os.getenv("AZURE_STORAGE_ACCOUNT_URL")

AZURE_TENANT_ID = os.getenv("AZURE_TENANT_ID")

AZURE_CLIENT_ID = os.getenv("AZURE_CLIENT_ID")

AZURE_CLIENT_SECRET = os.getenv("AZURE_CLIENT_SECRET")

AZURE_CONTAINER_NAME = os.getenv("AZURE_CONTAINER_NAME")


# ---------------------------------------------------------------------------
# Redis
# ---------------------------------------------------------------------------

REDIS_HOST = os.getenv("REDIS_HOST")

REDIS_PORT = os.getenv("REDIS_PORT")

REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")

REDIS_SSL = (
    os.getenv("REDIS_SSL", "False").strip().lower() == "true"
)


# ---------------------------------------------------------------------------
# Custom checker
# ---------------------------------------------------------------------------

CUSTOM_CHECKER_DIR = os.getenv("CUSTOM_CHECKER_DIR")


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

LOGS_DIR = os.path.join(BASE_DIR, "logs")

# Ensure the log directory exists before Django configures the file handler.
os.makedirs(LOGS_DIR, exist_ok=True)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module} | {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(LOGS_DIR, "project.log"),
            "formatter": "verbose",
        },
    },

    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "problems": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}