# Generated by Django 5.2.3 on 2026-10-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='genie_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes Section from Polygon', null=True),
        ),
    ]
